name: Character_Gen_DD5
description: A dnd 5e character creator app. Not my first attempt, but still a fairly preliminary attempt. A learn-as-I-go project.
dependencies:
  core_elements: any
  intl: any
  paper_elements: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
